In [3]:
import numpy as np

In [7]:
side = np.array([1,2,3])
print sidex

[1 2 3]


In [9]:
side2 = np.array([[1,2,3],[4,5,6]])
print side2

[[1 2 3]
 [4 5 6]]


In [12]:
side3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print side3

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [23]:
array1x8 = np.array(["x1y1","x1y2","x1y3","x1y4","x1y5","x1y6","x1y7","x1y8"])
print array1x8                

['x1y1' 'x1y2' 'x1y3' 'x1y4' 'x1y5' 'x1y6' 'x1y7' 'x1y8']


In [35]:
array5x8 = np.array([array1x8,array1x8,array1x8,array1x8,array1x8])
print array5x8

[['x1y1' 'x1y2' 'x1y3' 'x1y4' 'x1y5' 'x1y6' 'x1y7' 'x1y8']
 ['x1y1' 'x1y2' 'x1y3' 'x1y4' 'x1y5' 'x1y6' 'x1y7' 'x1y8']
 ['x1y1' 'x1y2' 'x1y3' 'x1y4' 'x1y5' 'x1y6' 'x1y7' 'x1y8']
 ['x1y1' 'x1y2' 'x1y3' 'x1y4' 'x1y5' 'x1y6' 'x1y7' 'x1y8']
 ['x1y1' 'x1y2' 'x1y3' 'x1y4' 'x1y5' 'x1y6' 'x1y7' 'x1y8']]


In [44]:
#Set 1 - Add
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]

import numpy as np

z = np.add(a,b)
print z

#Set 2 - Subtract
a = [-1, -2, -3, -4, -5, -6]
b = [-6, -5, -4, -3, -2, -1]

z = np.subtract(a,b)
print z

#Set 3 - Subtract
a = [101, 201, 33.22, -423, 5.3234, -6.234]
b = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]

z = np.subtract(a,b)
print z

#Set 4 - Subtract
a = [-101, -201, -33.22, 423, -5.3234, -34]
b = [601, -501.33, 113, -3.3000003, 'l', 10.999999999999999]


for index, value in enumerate(b):
    print index, value
    print type(value)
    if type(value) == str:
        print "found str"
        b[index] = 0
        
z = np.subtract(a,b)
print z

z = np.dot(a,b)
print z

[-5 -3 -1  1  3  5]
[ 5  3  1 -1 -3 -5]
[ 702.        -300.33       146.22      -426.3000003    7.3234      -4.234    ]
0 601
<type 'int'>
1 -501.33
<type 'float'>
2 113
<type 'int'>
3 -3.3000003
<type 'float'>
4 l
<type 'str'>
found str
5 11.0
<type 'float'>
[-702.         300.33      -146.22       426.3000003   -5.3234     -45.       ]
34542.5698731


In [50]:
side1 = np.array([1])
#print sidex #1D
side2 = np.array([side1*1,side1*2])
#print side2 #2D
side3 = np.array([side2*1, side2*2, side2*3])
print "3D"
print side3 #3D
side4 = np.array([side3*1, side3*2, side3*3, side3*4])
#print side4 #4D
side5 = np.array([side4*1, side4*2, side4*3, side4*4, side4*5])
print "5D"
print side5 #5D

3D
[[[1]
  [2]]

 [[2]
  [4]]

 [[3]
  [6]]]
5D
[[[[[  1]
    [  2]]

   [[  2]
    [  4]]

   [[  3]
    [  6]]]


  [[[  2]
    [  4]]

   [[  4]
    [  8]]

   [[  6]
    [ 12]]]


  [[[  3]
    [  6]]

   [[  6]
    [ 12]]

   [[  9]
    [ 18]]]


  [[[  4]
    [  8]]

   [[  8]
    [ 16]]

   [[ 12]
    [ 24]]]]



 [[[[  2]
    [  4]]

   [[  4]
    [  8]]

   [[  6]
    [ 12]]]


  [[[  4]
    [  8]]

   [[  8]
    [ 16]]

   [[ 12]
    [ 24]]]


  [[[  6]
    [ 12]]

   [[ 12]
    [ 24]]

   [[ 18]
    [ 36]]]


  [[[  8]
    [ 16]]

   [[ 16]
    [ 32]]

   [[ 24]
    [ 48]]]]



 [[[[  3]
    [  6]]

   [[  6]
    [ 12]]

   [[  9]
    [ 18]]]


  [[[  6]
    [ 12]]

   [[ 12]
    [ 24]]

   [[ 18]
    [ 36]]]


  [[[  9]
    [ 18]]

   [[ 18]
    [ 36]]

   [[ 27]
    [ 54]]]


  [[[ 12]
    [ 24]]

   [[ 24]
    [ 48]]

   [[ 36]
    [ 72]]]]



 [[[[  4]
    [  8]]

   [[  8]
    [ 16]]

   [[ 12]
    [ 24]]]


  [[[  8]
    [ 16]]

   [[ 16]
    [ 32]]

   [[ 24]
    [ 48

In [7]:
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]

z = np.dot(a,b)
print z

-56


In [8]:
x = 4**4
x = np.arange(0,x)
y = a.reshape(4,4,4,4)
print y

AttributeError: 'list' object has no attribute 'reshape'