In [22]:
# import numpy
# create array x

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print a[2]

3


In [2]:
# print the shape of x

In [3]:
# create a two dimensional array

In [4]:
# print shape of 2d array

In [5]:
# reshape the array to 2 x 6

In [8]:
# reshape the array to 1 x 12
z = np.array([a,b])
print z

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [25]:
c = a + b
c2 = np.add(a,b)
print c
print c2
#transpose the array
T0 = z[:,0]
T1 = z[:,1]
T2 = z[:,2]
T3 = z[:,3]
T4 = z[:,4]
T = np.array([T0, T1, T2, T3, T4])
print T


for index, value in enumerate(X):
    print index, value
    X = np.array(value)
print len(T)



[6 6 6 6 6]
[6 6 6 6 6]
[[1 5]
 [2 4]
 [3 3]
 [4 2]
 [5 1]]
0 [1 5]
1 [2 4]
2 [3 3]
3 [4 2]
4 [5 1]
5


In [8]:
# indexing method 1

In [9]:
# indexing method 2

In [13]:
# indexing method 3

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6